# Generated by Django 3.0.7 on 2020-07-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
