# Generated by Django 3.0.5 on 2020-05-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
