# Generated by Django 3.0.5 on 2020-05-26 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='report_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_profiles',
            field=models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
