# Generated by Django 3.0.7 on 2020-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200526_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_likes',
            field=models.IntegerField(default=0),
        ),
    ]
