# Generated by Django 3.0.7 on 2020-06-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200609_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_width_height',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_width_height', null=True, upload_to='', width_field='avatar_width_height'),
        ),
    ]
