# Generated by Django 3.0.7 on 2020-06-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200609_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_width_height',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
