# Generated by Django 3.0.7 on 2020-06-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200610_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatar',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Profile')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profileImages')),
            ],
        ),
        migrations.DeleteModel(
            name='DummyProfilePic',
        ),
    ]
