# Generated by Django 3.0.7 on 2020-06-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='all_likes',
            new_name='total_likes',
        ),
    ]
