# Generated by Django 3.0.7 on 2020-06-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200620_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_likes',
        ),
    ]
