# Generated by Django 3.0.7 on 2020-06-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_profile_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
