# Generated by Django 3.0.7 on 2020-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
