# Generated by Django 3.0.7 on 2020-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200620_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='user',
            name='report_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
