# Generated by Django 3.0.7 on 2020-07-09 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_profile_blocked_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_profiles',
            field=models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
