# Generated by Django 3.0.7 on 2020-07-10 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_profile_blocked_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked_profiles',
            field=models.ManyToManyField(related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
