# Generated by Django 3.0.7 on 2020-07-10 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200710_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked_profiles',
            field=models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
