# Generated by Django 2.2.7 on 2019-11-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='likes_count',
        ),
    ]
