# Generated by Django 3.0.5 on 2020-04-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200404_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_url',
        ),
    ]
