# Generated by Django 3.0.5 on 2020-04-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='report_counter',
            field=models.IntegerField(default=0),
        ),
    ]
