# Generated by Django 3.0.7 on 2020-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_report_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_time',
            field=models.IntegerField(default=1),
        ),
    ]
