# Generated by Django 3.0.7 on 2020-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='report_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
