# Generated by Django 3.0.7 on 2020-07-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
