# Generated by Django 3.1.2 on 2020-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200821_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='audio_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
