# Generated by Django 3.1.2 on 2020-10-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20201023_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='items',
            field=models.ManyToManyField(related_name='hashtags', to='items.Item'),
        ),
    ]
