# Generated by Django 3.1.2 on 2020-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20201024_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_audio_image',
            field=models.BooleanField(default=False),
        ),
    ]
