# Generated by Django 3.1.2 on 2020-11-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_custom_audio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='custom_audio_image',
        ),
    ]
