# Generated by Django 3.1.2 on 2020-12-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_remove_item_custom_audio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_time',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
