# Generated by Django 3.1.2 on 2021-01-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20201215_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status_blue',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status_green',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status_red',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
