# Generated by Django 3.1.2 on 2021-01-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20210121_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status_blue',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_green',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_red',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
