# Generated by Django 3.1.5 on 2021-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20210122_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status_blue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_green',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_red',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
