# Generated by Django 3.1.5 on 2021-02-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20210212_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expiry_time',
        ),
    ]
