# Generated by Django 3.0.5 on 2020-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='badge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
