# Generated by Django 3.0.7 on 2020-06-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200428_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='badge_count',
        ),
    ]
