# Generated by Django 3.0.8 on 2020-07-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_badge_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('created_at',)},
        ),
    ]
